#!/bin/bash
set -e

# build.config を読み込む
. script/build.config

PROJECT_NAME="RetroArch_iOS13.xcodeproj"

# クリーン
xcodebuild clean -project "$PROJECT_NAME"
rm -rf build

# ビルドコマンド
if [ -z "$NOCODESIGN" ]; then
    echo "Building RetroArch iOS (no codesign)"
    xcodebuild -verbose \
        -project "$PROJECT_NAME" \
        -scheme "RetroArch iOS Release" \
        -sdk iphoneos \
        -configuration Release \
        CODE_SIGNING_ALLOWED=NO \
        CODE_SIGNING_REQUIRED=NO
else
    echo "Building RetroArch iOS (Jailbroken / no codesign)"
    xcodebuild -verbose \
        -project "$PROJECT_NAME" \
        -scheme "RetroArch iOS Release" \
        -sdk iphoneos \
        -configuration Release \
        CODE_SIGNING_ALLOWED=NO \
        CODE_SIGNING_REQUIRED=NO
fi

echo "######### RetroArch build Complete! #########"
echo "You can find the resulting app in the $BUILD_PATH directory."echo "All Clang dependency info collected in $DEPS_FILE"
